server:
  port: 31000

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fatbun/spring-cloud-config
#          username:
#          password:
          #默认是秒，因为git慢
          timeout: 15

eureka:
  # eureka.instance.appname
  # eureka.instance.virtualHostName
  # eureka.instance.secureVirtualHostName
  # 会取spring.application.name，否则UNKOWN
  instance:
    #续约发送间隔默认30秒，心跳间隔
    lease-renewal-interval-in-seconds: 5
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 60
  client:
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    registry-fetch-interval-seconds: 5
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://euk1.com:7001/eureka/,http://euk2.com:7002/eureka/
